# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # ...
    # App\DataTransformer\PortionFriteOutputTransformer:
    #     # Uncomment only if autoconfiguration is disabled
    #     tags: [ 'api_platform.data_transformer' ]
    # App\DataTransformer\PortionFriteInputTransformer:
    #     # Uncomment only if autoconfiguration is disabled
    #     tags: [ 'api_platform.data_transformer' ]

    # App\Controller\:
    #     resource: '../src/Controller/'
    #     tags: ['controller.service_arguments']
    # App\EventSubscriber\UserSubscriber:
    #     tags: 
    #         - { name: doctrine.event_listener, event: prePersist}

    # App\EventSubscriber\BoissonSubscriber:
    #     tags: 
    #         - { name: doctrine.event_listener, event: prePersist}

    # App\EventSubscriber\MenuSubscriber:
    #     tags: 
    #         - { name: doctrine.event_listener, event: prePersist}

    # App\EventSubscriber\BurgerSubscriber:
    #     tags: 
    #         - { name: doctrine.event_listener, event: prePersist}
            
    # App\EventSubscriber\DecodeService:
    #     tags: 
    #         - { name: kernel.event_listener, event: kernel.REQUEST }
    
    # App\DataProvider\BurgerDataProvider':
    #     tags: [ { name: 'api_platform.collection_data_provider', priority: 2 } ]

    # App\DataProvider\CatalogueDataProvider':
    #     tags: [ { name: 'api_platform.collection_data_provider', priority: 2 } ]
    #     # Autoconfiguration must be disabled to set a custom priority
    #     autoconfigure: false

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
